name: LSD
fullname: Lovely Scalable Drawings
filename: lsd.js
description: Psychodelically awesome library for UI in javascript and SVG
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.4prealpha
tags: [ui, svg, interface]
demo: http://inviz.ru/lsd/Dependencies/lsd-examples/Demos/index.html
sources:
  - Source/LSD.js
  - Source/DOM/Node.js
  - Source/DOM/Element.js
  - Source/DOM/Textnode.js
  - Source/DOM/Fragment.js
  - Source/DOM/Comment.js
  - Source/DOM/Instruction.js
  - Source/DOM/Document.js
  - Source/DOM/Range.js
  - Source/DOM/NodeList.js
  - Source/DOM/ChildNodes.js
  - Source/Type/Object.js
  - Source/Type/Journal.js
  - Source/Type/Group.js
  - Source/Type/Struct.js
  - Source/Type/Array.js
  - Source/Type/Data.js
  - Source/Type/RegExp.js
  - Source/Properties/ClassList.js
  - Source/Properties/Matches.js
  - Source/Properties/Relations.js
  - Source/Properties/Attributes.js
  - Source/Properties/Events.js
  - Source/Properties/Resource.js
  - Source/Properties/Proxies.js
  - Source/Properties/Roles.js
  - Source/Properties/Styles.js
  - Source/Properties/Microdata.js
  - Source/Script/Script.js
  - Source/Script/Parser.js
  - Source/Script/Helpers.js