name: LSD
fullname: Lovely Scalable Drawings
filename: lsd.js
description: Psychodelically awesome library for UI in javascript and SVG
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.4prealpha
tags: [ui, svg, interface]
demo: http://inviz.ru/lsd/Dependencies/lsd-examples/Demos/index.html
sources:
  - Source/LSD.js
  - Source/Node/Element.js
  - Source/Node/Textnode.js
  - Source/Node/Fragment.js
  - Source/Node/Comment.js
  - Source/Node/Instruction.js
  - Source/Node/Document.js
  - Source/Object/Object.js
  - Source/Object/Object.Stack.js
  - Source/Object/Object.Group.js
  - Source/Object/Struct.js
  - Source/Object/Array.js
  - Source/Object/NodeList.js
  - Source/Properties/ChildNodes.js
  - Source/Properties/ClassList.js
  - Source/Properties/Matches.js
  - Source/Properties/Elements.js
  - Source/Properties/Relations.js
  - Source/Properties/Attributes.js
  - Source/Properties/Events.js
  - Source/Properties/Resource.js
  - Source/Script/Script.js
  - Source/Script/Function.js
  - Source/Script/Parser.js
  - Source/Script/Helpers.js
  - Source/Script/Block.js
  - Source/Script/Selector.js