name: LSD
fullname: Lovely Scalable Drawings
filename: lsd.js
description: Psychodelically awesome library for UI in javascript and SVG
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.4prealpha
tags: [ui, svg, interface]
demo: http://inviz.ru/lsd/Dependencies/lsd-examples/Demos/index.html
sources:
  - Source/ART/ART.js
  - Source/ART/ART.SVG.js
  - Source/ART/ART.Element.js
  - Source/ART/ART.Glyphs.js
  - Source/ART/ART.Shape.Arrow.js
  - Source/ART/ART.Shape.Ellipse.js
  - Source/ART/ART.Shape.Flower.js
  - Source/ART/ART.Shape.Rectangle.js
  - Source/ART/ART.Shape.Star.js
  - Source/Tools/Behavior.js
  - Source/Tools/Object.js
  - Source/Tools/Helpers.js
  - Source/Tools/Command.js
  - Source/Tools/Require.js
  - Source/Tools/Position.js
  - Source/Document.js
  - Source/LSD.js
  - Source/Type.js
  - Source/Relation.js
  - Source/Layer.js
  - Source/Layer/Color.js
  - Source/Layer/Offset.js
  - Source/Layer/Position.js
  - Source/Layer/Radius.js
  - Source/Layer/Shadow.Blur.js
  - Source/Layer/Shadow.Inset.js
  - Source/Layer/Shadow.js
  - Source/Layer/Shadow.Native.js
  - Source/Layer/Shadow.Onion.js
  - Source/Layer/Shape.js
  - Source/Layer/Size.js
  - Source/Layer/Scale.js
  - Source/Layer/Stroke.js
  - Source/Mixin/Submittable.js
  - Source/Mixin/Fieldset.js
  - Source/Mixin/Draggable.js
  - Source/Mixin/Resizable.js
  - Source/Mixin/Scrollable.js
  - Source/Mixin/Touchable.js
  - Source/Mixin/Placeholder.js
  - Source/Mixin/Focusable.js
  - Source/Mixin/Request.js
  - Source/Mixin/Resource.js
  - Source/Mixin/Validity.js
  - Source/Mixin/Value.js
  - Source/Mixin/Animation.js
  - Source/Mixin/Uploader.js
  - Source/Mixin/Unselectable.js
  - Source/Mixin/ContentEditable.js
  - Source/Mixin/Choice.js
  - Source/Mixin/List.js
  - Source/Mixin/Command.js
  - Source/Mixin/Target.js
  - Source/Mixin/Root.js
  - Source/Mixin/Sortable.js
  - Source/Mixin/Invokable.js
  - Source/Mixin/Slider.js
  - Source/Mixin/Date.js
  - Source/Module/Ambient/Allocations.js
  - Source/Module/Ambient/DOM.js
  - Source/Module/Ambient/Selectors.js
  - Source/Module/Ambient/Expectations.js
  - Source/Module/Ambient/Mutations.js
  - Source/Module/Ambient/Layout.js
  - Source/Module/Ambient/Relations.js
  - Source/Module/Ambient/Proxies.js
  - Source/Module/Ambient/Interpolations.js
  - Source/Module/Ambient.js
  - Source/Module/Accessories/Chain.js
  - Source/Module/Accessories/Actions.js
  - Source/Module/Accessories/Styles.js
  - Source/Module/Accessories/Attributes.js
  - Source/Module/Accessories/Events.js
  - Source/Module/Accessories/Dimensions.js
  - Source/Module/Accessories/Shortcuts.js
  - Source/Module/Accessories/Options.js
  - Source/Module/Accessories/States.js
  - Source/Module/Accessories/Element.js
  - Source/Module/Accessories/Mixins.js
  - Source/Module/Accessories/Properties.js
  - Source/Module/Accessories.js
  - Source/Module/Graphics/Render.js
  - Source/Module/Graphics/Layers.js
  - Source/Module/Graphics/Shape.js
  - Source/Module/Graphics.js
  - Source/Trait/Input.js
  - Source/Action/Create.js
  - Source/Action/Update.js
  - Source/Action/Delete.js
  - Source/Action/Submit.js
  - Source/Action/State.js
  - Source/Action/Set.js
  - Source/Action/List.js
  - Source/Action/Display.js
  - Source/Action/Toggle.js
  - Source/Action/Clone.js
  - Source/Action/Edit.js
  - Source/Action/History.js
  - Source/Action/Focus.js
  - Source/Action/Counter.js
  - Source/Action/Invoke.js
  - Source/Action/Attribute.js
  - Source/Action.js
  - Source/Script.js
  - Source/Script/Variable.js
  - Source/Script/Function.js
  - Source/Script/Selector.js
  - Source/Script/Helpers.js
  - Source/Layout.js
  - Source/Layout/Branch.js
  - Source/Layout/Microdata.js
  - Source/Layout/Promise.js
  - Source/Sheet.js
  - Source/Widget.js