name: LSD
fullname: Lovely Scalable Drawings
filename: lsd.js
description: Psychodelically awesome library for UI in javascript and SVG
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.4prealpha
tags: [ui, svg, interface]
demo: http://inviz.ru/lsd/Dependencies/lsd-examples/Demos/index.html
sources:
  - Source/LSD.js
  - Source/LSD/Widget.js
  - Source/LSD/Namespace.js
  - Source/Object/Object.js
  - Source/Object/Object.Stack.js
  - Source/Object/Object.Group.js
  - Source/Object/Struct.js
  - Source/Object/Array.js
  - Source/ART/ART.js
  - Source/ART/ART.SVG.js
  - Source/ART/ART.Element.js
  - Source/ART/ART.Glyphs.js
  - Source/ART/ART.Shape.Arrow.js
  - Source/ART/ART.Shape.Ellipse.js
  - Source/ART/ART.Shape.Flower.js
  - Source/ART/ART.Shape.Rectangle.js
  - Source/ART/ART.Shape.Star.js
  - Source/Tools/Helpers.js
  - Source/Tools/Require.js
  - Source/Tools/Logger.js
  - Source/Type/Children.js
  - Source/Type/States.js
  - Source/Type/Matches.js
  - Source/Type/Relations.js
  - Source/Type/Attributes.js
  - Source/Type/Events.js
  - Source/Type/Allocations.js