name: LSD
fullname: Lovely Scalable Drawings
filename: lsd.js
description: Psychodelically awesome library for UI in javascript and SVG
license: Public domain, http://unlicense.org
copyright: Yaroslaff Fedin
author: inviz
category: Interface
current: 0.4prealpha
tags: [ui, svg, interface]
demo: http://inviz.ru/lsd/Dependencies/lsd-examples/Demos/index.html
sources:
  - Source/ART/ART.js
  - Source/ART/ART.SVG.js
  - Source/ART/ART.Element.js
  - Source/ART/ART.Glyphs.js
  - Source/ART/ART.Shape.Arrow.js
  - Source/ART/ART.Shape.Ellipse.js
  - Source/ART/ART.Shape.Flower.js
  - Source/ART/ART.Shape.Rectangle.js
  - Source/ART/ART.Shape.Star.js
  - Source/Application.js
  - Source/Command/Command.js
  - Source/Command/Checkbox.js
  - Source/Command/Radio.js
  - Source/Document.js
  - Source/Document/Resizable.js
  - Source/Document/Commands.js
  - Source/LSD.js
  - Source/Layer.js
  - Source/Layer/Color.js
  - Source/Layer/Offset.js
  - Source/Layer/Position.js
  - Source/Layer/Radius.js
  - Source/Layer/Shadow.Blur.js
  - Source/Layer/Shadow.Inset.js
  - Source/Layer/Shadow.js
  - Source/Layer/Shadow.Native.js
  - Source/Layer/Shadow.Onion.js
  - Source/Layer/Shape.js
  - Source/Layer/Size.js
  - Source/Layer/Scale.js
  - Source/Layer/Stroke.js
  - Source/Mixin/Draggable.js
  - Source/Mixin/Resizable.js
  - Source/Mixin/Scrollable.js
  - Source/Mixin/Touchable.js
  - Source/Mixin/Position.js
  - Source/Mixin/Focus.js
  - Source/Mixin/Request.js
  - Source/Mixin/Resource.js
  - Source/Mixin/Validity.js
  - Source/Mixin/Dialog.js
  - Source/Module/Container.js
  - Source/Module/Command.js
  - Source/Module/DOM.js
  - Source/Module/Expectations.js
  - Source/Module/Layout.js
  - Source/Module/Styles.js
  - Source/Module/Attributes.js
  - Source/Module/Events.js
  - Source/Module/Actions.js
  - Source/Module/Render.js
  - Source/Module/Target.js
  - Source/Trait/Dimensions.js
  - Source/Trait/Proxies.js
  - Source/Trait/Layers.js
  - Source/Trait/Menu.js
  - Source/Trait/Shape.js
  - Source/Trait/Accessibility.js
  - Source/Trait/Animation.js
  - Source/Trait/Choice.js
  - Source/Trait/List.js
  - Source/Trait/Item.js
  - Source/Trait/Observer.js
  - Source/Trait/Value.js
  - Source/Trait/Input.js
  - Source/Trait/Slider.js
  - Source/Trait/Form.js
  - Source/Trait/Fieldset.js
  - Source/Trait/Field.js
  - Source/Trait/Date.js
  - Source/Action/Create.js
  - Source/Action/Update.js
  - Source/Action/Delete.js
  - Source/Action/Value.js
  - Source/Action/Replace.js
  - Source/Action/Send.js
  - Source/Action/State.js
  - Source/Action/Display.js
  - Source/Action/Dialog.js
  - Source/Action/Check.js
  - Source/Action.js
  - Source/Container.js
  - Source/Element.js
  - Source/Layout.js
  - Source/Fx.js
  - Source/Node.js
  - Source/Node/Link.js
  - Source/Sheet.js
  - Source/Native.js
  - Source/Widget.js
  - Source/Widget.Paint.js